### ISSUE TITLE
Problema com Favicon

### ISSUE THREAD

**Issue by DaniloLMD** [ronar01/html-css#1]
Boa tarde Ronar01. Gostaria de entender como você conseguiu colocar favicon no seu site do Android (desafio 10.1), copiei seu código e colei no meu projeto html mas ainda assim não funcionou.

**Comment by ronar01** [comment]
Olá sr. Danilo Lambi Madeira Dura.
Poderia por favor me dar a parte do seu código da qual se refere ao seu favico?

**Comment by DaniloLMD** [comment]
![img-erro-html](https://user-images.githubusercontent.com/124076190/216395566-914f433c-a46d-4202-84c5-2d56e261aecf.PNG)

Segue em anexo um print do código. Em vermelho, a parte do código que inicialmente fiz (e coincidentemente é igual à sua, até copiei do seu perfil e colei por cima para ter certeza) porém que não funciona. Em azul, a parte de um código de outro projeto meu que conseguiu realizar o favicon corretamente.
